rigs = [
  { id = "airspy0", model = "soapysdr", name = "AirspyHF" }
]

[general]
callsign = "N0CALL"
log_level = "debug"

[listen]
enabled = true
listen = "127.0.0.1"
port = 4530

[listen.auth]
tokens = []

[audio]
enabled = true
listen = "127.0.0.1"
port = 4531
rx_enabled = true
sample_rate = 48000

[airspy0.access]
type = "sdr"
args = "driver=AirspyHF,serial=c852eb5dd23539f8"
